# 
doc-valid-idents= [
"SELinux", 
"CategorySet", 
"SELINUX_MAGIC", 
"ProcFS", 
"GLOBAL_TRANSLATOR",
"RwLock",
"StaticSource", 
"SecureReader",
"SystemLow",
"PhantomData",
"FsMagic",
"ATTRIBUTE_NAME" ]
