[package]
name = "umrs-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
colored = "2.0"
gettext-rs = "0.7.7"
humansize = "2.1.3"
