[package]
name = "vaultmgr"
version = "0.1.0"
edition = "2024"

[dependencies]
umrs-core = { path = "../umrs-core" }
colored = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = "0.2"

