[workspace]
resolver = "2"
members = [
    "cui-labels", "kernel-files", 
    "robotgen", 
    "umrs-core",
    "umrs-logspace", "umrs-selinux", "umrs-semanage", "umrs-sepolicy",
    "umrs-state",
    "vaultmgr", 
    "xtask", 
]
