[package]
name = "umrs-state"
version = "0.1.0"
edition = "2021"

[dependencies]
umrs-core = { path = "../umrs-core" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
syslog = "6"
colored = "2.0"
