[package]
name = "umrs-logspace"
version = "0.1.0"
edition = "2021"

[dependencies]
glob  = "0.3"
clap  = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml  = "0.8"
nix   = { version = "0.28", features = ["fs"] }
walkdir = "2.5"
serde_json = "1.0"
